// <auto-generated />
using System;
using BuildMart.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BuildMart.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260819213109_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BuildMart.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("BuildMart.Domain.Entities.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Carts", (string)null);
                });

            modelBuilder.Entity("BuildMart.Domain.Entities.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("CartId", "ProductId")
                        .IsUnique();

                    b.ToTable("CartItems", (string)null);
                });

            modelBuilder.Entity("BuildMart.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Electric and battery-powered tools for professional and DIY work.",
                            ImageUrl = "/images/categories/power-tools.jpg",
                            Name = "Power Tools"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Manual tools for everyday construction and repair tasks.",
                            ImageUrl = "/images/categories/hand-tools.jpg",
                            Name = "Hand Tools"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cement, concrete mix, adhesives and waterproofing materials.",
                            ImageUrl = "/images/categories/construction-materials.jpg",
                            Name = "Construction Materials"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Personal protective equipment for job sites.",
                            ImageUrl = "/images/categories/safety-equipment.jpg",
                            Name = "Safety Equipment"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Rollers, brushes, trays and surface prep tools.",
                            ImageUrl = "/images/categories/painting-tools.jpg",
                            Name = "Painting Tools"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Tools and accessories for electrical installation work.",
                            ImageUrl = "/images/categories/electrical-tools.jpg",
                            Name = "Electrical Tools"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Tools and fittings for plumbing and pipework.",
                            ImageUrl = "/images/categories/plumbing-tools.jpg",
                            Name = "Plumbing Tools"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Fasteners, hinges and general hardware supplies.",
                            ImageUrl = "/images/categories/hardware.jpg",
                            Name = "Hardware"
                        });
                });

            modelBuilder.Entity("BuildMart.Domain.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("OrderDate");

                    b.HasIndex("OrderStatus");

                    b.HasIndex("UserId");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("BuildMart.Domain.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems", (string)null);
                });

            modelBuilder.Entity("BuildMart.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<decimal?>("DiscountPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(10,3)");

                    b.HasKey("Id");

                    b.HasIndex("Brand");

                    b.HasIndex("CategoryId");

                    b.HasIndex("IsAvailable");

                    b.HasIndex("Name");

                    b.HasIndex("Price");

                    b.HasIndex("SKU")
                        .IsUnique();

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Bosch",
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Variable-speed corded electric drill with keyless chuck.",
                            DiscountPrice = 39.900m,
                            ImageUrl = "/images/products/electric-drill.jpg",
                            IsAvailable = true,
                            Name = "Electric Drill 750W",
                            Price = 45.900m,
                            SKU = "PWR-DRL-001",
                            StockQuantity = 40,
                            Unit = "Piece",
                            Weight = 1.800m
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Makita",
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "850W angle grinder for cutting and grinding metal.",
                            ImageUrl = "/images/products/angle-grinder.jpg",
                            IsAvailable = true,
                            Name = "Angle Grinder 115mm",
                            Price = 38.500m,
                            SKU = "PWR-GRD-002",
                            StockQuantity = 25,
                            Unit = "Piece",
                            Weight = 2.100m
                        },
                        new
                        {
                            Id = 3,
                            Brand = "DeWalt",
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Corded circular saw with laser guide for straight cuts.",
                            DiscountPrice = 54.900m,
                            ImageUrl = "/images/products/circular-saw.jpg",
                            IsAvailable = true,
                            Name = "Circular Saw 1200W",
                            Price = 62.000m,
                            SKU = "PWR-SAW-003",
                            StockQuantity = 15,
                            Unit = "Piece",
                            Weight = 3.400m
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Makita",
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cordless impact driver with 2 batteries and fast charger.",
                            ImageUrl = "/images/products/impact-driver.jpg",
                            IsAvailable = true,
                            Name = "Impact Driver 18V",
                            Price = 58.750m,
                            SKU = "PWR-IMD-004",
                            StockQuantity = 30,
                            Unit = "Piece",
                            Weight = 1.500m
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Bosch",
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Battery-powered jigsaw for curved and straight cuts.",
                            ImageUrl = "/images/products/jigsaw.jpg",
                            IsAvailable = true,
                            Name = "Cordless Jigsaw 18V",
                            Price = 41.200m,
                            SKU = "PWR-JIG-005",
                            StockQuantity = 20,
                            Unit = "Piece",
                            Weight = 1.900m
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Stanley",
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Fiberglass handle claw hammer with shock-absorbing grip.",
                            ImageUrl = "/images/products/claw-hammer.jpg",
                            IsAvailable = true,
                            Name = "Claw Hammer 16oz",
                            Price = 8.900m,
                            SKU = "HND-HMR-006",
                            StockQuantity = 100,
                            Unit = "Piece",
                            Weight = 0.600m
                        },
                        new
                        {
                            Id = 7,
                            Brand = "Stanley",
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Assorted flathead and Phillips screwdrivers with magnetic tips.",
                            DiscountPrice = 11.900m,
                            ImageUrl = "/images/products/screwdriver-set.jpg",
                            IsAvailable = true,
                            Name = "Screwdriver Set 12-Piece",
                            Price = 14.500m,
                            SKU = "HND-SCD-007",
                            StockQuantity = 60,
                            Unit = "Set",
                            Weight = 0.900m
                        },
                        new
                        {
                            Id = 8,
                            Brand = "Irwin",
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Chrome vanadium steel adjustable wrench.",
                            ImageUrl = "/images/products/adjustable-wrench.jpg",
                            IsAvailable = true,
                            Name = "Adjustable Wrench 10-inch",
                            Price = 9.750m,
                            SKU = "HND-WRN-008",
                            StockQuantity = 80,
                            Unit = "Piece",
                            Weight = 0.400m
                        },
                        new
                        {
                            Id = 9,
                            Brand = "Irwin",
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Heavy-duty combination pliers with insulated grip.",
                            ImageUrl = "/images/products/combination-pliers.jpg",
                            IsAvailable = true,
                            Name = "Combination Pliers 8-inch",
                            Price = 7.200m,
                            SKU = "HND-PLR-009",
                            StockQuantity = 90,
                            Unit = "Piece",
                            Weight = 0.300m
                        },
                        new
                        {
                            Id = 10,
                            Brand = "Stanley",
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Retractable steel measuring tape with locking mechanism.",
                            ImageUrl = "/images/products/measuring-tape.jpg",
                            IsAvailable = true,
                            Name = "Measuring Tape 8m",
                            Price = 6.500m,
                            SKU = "HND-TAP-010",
                            StockQuantity = 120,
                            Unit = "Piece",
                            Weight = 0.250m
                        },
                        new
                        {
                            Id = 11,
                            Brand = "LafargeHolcim",
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "General-purpose Portland cement, high-strength grade.",
                            ImageUrl = "/images/products/cement-bag.jpg",
                            IsAvailable = true,
                            Name = "Portland Cement 50kg",
                            Price = 4.200m,
                            SKU = "MAT-CEM-011",
                            StockQuantity = 500,
                            Unit = "Bag",
                            Weight = 50.000m
                        },
                        new
                        {
                            Id = 12,
                            Brand = "Quikrete",
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Pre-mixed concrete, just add water.",
                            ImageUrl = "/images/products/concrete-mix.jpg",
                            IsAvailable = true,
                            Name = "Ready Concrete Mix 40kg",
                            Price = 5.800m,
                            SKU = "MAT-CON-012",
                            StockQuantity = 300,
                            Unit = "Bag",
                            Weight = 40.000m
                        },
                        new
                        {
                            Id = 13,
                            Brand = "Weber",
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cement-based adhesive for ceramic and porcelain tiles.",
                            ImageUrl = "/images/products/tile-adhesive.jpg",
                            IsAvailable = true,
                            Name = "Tile Adhesive 25kg",
                            Price = 6.900m,
                            SKU = "MAT-ADH-013",
                            StockQuantity = 200,
                            Unit = "Bag",
                            Weight = 25.000m
                        },
                        new
                        {
                            Id = 14,
                            Brand = "Sika",
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Liquid-applied waterproofing membrane for roofs and terraces.",
                            DiscountPrice = 27.500m,
                            ImageUrl = "/images/products/waterproofing.jpg",
                            IsAvailable = true,
                            Name = "Waterproofing Membrane 10L",
                            Price = 32.000m,
                            SKU = "MAT-WPF-014",
                            StockQuantity = 60,
                            Unit = "Liter",
                            Weight = 10.500m
                        },
                        new
                        {
                            Id = 15,
                            Brand = "Knauf",
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Interior wall and ceiling finishing plaster.",
                            ImageUrl = "/images/products/gypsum-plaster.jpg",
                            IsAvailable = true,
                            Name = "Gypsum Plaster 25kg",
                            Price = 5.100m,
                            SKU = "MAT-GYP-015",
                            StockQuantity = 250,
                            Unit = "Bag",
                            Weight = 25.000m
                        },
                        new
                        {
                            Id = 16,
                            Brand = "3M",
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "ANSI-rated hard hat with adjustable ratchet suspension.",
                            ImageUrl = "/images/products/safety-helmet.jpg",
                            IsAvailable = true,
                            Name = "Safety Helmet - Yellow",
                            Price = 6.900m,
                            SKU = "SAF-HLM-016",
                            StockQuantity = 150,
                            Unit = "Piece",
                            Weight = 0.400m
                        },
                        new
                        {
                            Id = 17,
                            Brand = "3M",
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Level 5 cut-resistant work gloves, size L.",
                            ImageUrl = "/images/products/safety-gloves.jpg",
                            IsAvailable = true,
                            Name = "Safety Gloves - Cut Resistant",
                            Price = 4.500m,
                            SKU = "SAF-GLV-017",
                            StockQuantity = 200,
                            Unit = "Piece",
                            Weight = 0.150m
                        },
                        new
                        {
                            Id = 18,
                            Brand = "3M",
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Anti-fog, anti-scratch polycarbonate safety glasses.",
                            ImageUrl = "/images/products/safety-glasses.jpg",
                            IsAvailable = true,
                            Name = "Safety Glasses - Clear",
                            Price = 3.200m,
                            SKU = "SAF-GLS-018",
                            StockQuantity = 180,
                            Unit = "Piece",
                            Weight = 0.050m
                        },
                        new
                        {
                            Id = 19,
                            Brand = "Generic",
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Reflective high-visibility vest, orange, one size fits most.",
                            ImageUrl = "/images/products/safety-vest.jpg",
                            IsAvailable = true,
                            Name = "Hi-Vis Safety Vest",
                            Price = 5.400m,
                            SKU = "SAF-VST-019",
                            StockQuantity = 160,
                            Unit = "Piece",
                            Weight = 0.200m
                        },
                        new
                        {
                            Id = 20,
                            Brand = "Caterpillar",
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Slip-resistant steel toe cap safety boots, size 42.",
                            DiscountPrice = 24.900m,
                            ImageUrl = "/images/products/work-boots.jpg",
                            IsAvailable = true,
                            Name = "Steel Toe Work Boots",
                            Price = 28.900m,
                            SKU = "SAF-BOT-020",
                            StockQuantity = 70,
                            Unit = "Piece",
                            Weight = 1.200m
                        },
                        new
                        {
                            Id = 21,
                            Brand = "Generic",
                            CategoryId = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Roller frame with two medium-nap sleeves.",
                            ImageUrl = "/images/products/paint-roller.jpg",
                            IsAvailable = true,
                            Name = "Paint Roller Set 9-inch",
                            Price = 6.200m,
                            SKU = "PNT-ROL-021",
                            StockQuantity = 140,
                            Unit = "Set",
                            Weight = 0.350m
                        },
                        new
                        {
                            Id = 22,
                            Brand = "Generic",
                            CategoryId = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Angled sash paint brush with synthetic bristles.",
                            ImageUrl = "/images/products/paint-brush.jpg",
                            IsAvailable = true,
                            Name = "Paint Brush 2-inch",
                            Price = 2.900m,
                            SKU = "PNT-BRS-022",
                            StockQuantity = 220,
                            Unit = "Piece",
                            Weight = 0.080m
                        },
                        new
                        {
                            Id = 23,
                            Brand = "Generic",
                            CategoryId = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Plastic paint tray with ribbed roller-off ramp.",
                            ImageUrl = "/images/products/paint-tray.jpg",
                            IsAvailable = true,
                            Name = "Paint Tray 9-inch",
                            Price = 3.500m,
                            SKU = "PNT-TRY-023",
                            StockQuantity = 130,
                            Unit = "Piece",
                            Weight = 0.220m
                        },
                        new
                        {
                            Id = 24,
                            Brand = "Stanley",
                            CategoryId = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Flexible stainless steel wall scraper for surface prep.",
                            ImageUrl = "/images/products/scraper.jpg",
                            IsAvailable = true,
                            Name = "Wall Scraper 4-inch",
                            Price = 4.100m,
                            SKU = "PNT-SCR-024",
                            StockQuantity = 110,
                            Unit = "Piece",
                            Weight = 0.150m
                        },
                        new
                        {
                            Id = 25,
                            Brand = "Klein Tools",
                            CategoryId = 6,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Automatic wire stripper for 10-24 AWG cable.",
                            ImageUrl = "/images/products/wire-stripper.jpg",
                            IsAvailable = true,
                            Name = "Wire Stripper Tool",
                            Price = 9.900m,
                            SKU = "ELC-WST-025",
                            StockQuantity = 75,
                            Unit = "Piece",
                            Weight = 0.200m
                        },
                        new
                        {
                            Id = 26,
                            Brand = "Fluke",
                            CategoryId = 6,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Auto-ranging digital multimeter for voltage, current and resistance.",
                            ImageUrl = "/images/products/multimeter.jpg",
                            IsAvailable = true,
                            Name = "Digital Multimeter",
                            Price = 22.500m,
                            SKU = "ELC-MTM-026",
                            StockQuantity = 45,
                            Unit = "Piece",
                            Weight = 0.350m
                        },
                        new
                        {
                            Id = 27,
                            Brand = "Rigid",
                            CategoryId = 7,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cast iron pipe wrench with serrated jaws.",
                            ImageUrl = "/images/products/pipe-wrench.jpg",
                            IsAvailable = true,
                            Name = "Pipe Wrench 14-inch",
                            Price = 16.800m,
                            SKU = "PLB-WRN-027",
                            StockQuantity = 55,
                            Unit = "Piece",
                            Weight = 1.100m
                        },
                        new
                        {
                            Id = 28,
                            Brand = "Generic",
                            CategoryId = 7,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "12m roll of PTFE tape for sealing pipe threads.",
                            ImageUrl = "/images/products/ptfe-tape.jpg",
                            IsAvailable = true,
                            Name = "PTFE Thread Seal Tape",
                            Price = 1.200m,
                            SKU = "PLB-TPE-028",
                            StockQuantity = 300,
                            Unit = "Piece",
                            Weight = 0.020m
                        },
                        new
                        {
                            Id = 29,
                            Brand = "Generic",
                            CategoryId = 8,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Zinc-plated wood screws, assorted sizes, 200-piece box.",
                            ImageUrl = "/images/products/wood-screws.jpg",
                            IsAvailable = true,
                            Name = "Assorted Wood Screws 200pc",
                            Price = 7.500m,
                            SKU = "HRD-SCR-029",
                            StockQuantity = 160,
                            Unit = "Box",
                            Weight = 1.000m
                        },
                        new
                        {
                            Id = 30,
                            Brand = "Generic",
                            CategoryId = 8,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Stainless steel butt hinges, pair, with mounting screws.",
                            ImageUrl = "/images/products/door-hinges.jpg",
                            IsAvailable = true,
                            Name = "Door Hinges 4-inch (Pair)",
                            Price = 5.900m,
                            SKU = "HRD-HNG-030",
                            StockQuantity = 100,
                            Unit = "Set",
                            Weight = 0.400m
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BuildMart.Domain.Entities.Cart", b =>
                {
                    b.HasOne("BuildMart.Domain.Entities.ApplicationUser", "User")
                        .WithOne("Cart")
                        .HasForeignKey("BuildMart.Domain.Entities.Cart", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BuildMart.Domain.Entities.CartItem", b =>
                {
                    b.HasOne("BuildMart.Domain.Entities.Cart", "Cart")
                        .WithMany("Items")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BuildMart.Domain.Entities.Product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BuildMart.Domain.Entities.Order", b =>
                {
                    b.HasOne("BuildMart.Domain.Entities.ApplicationUser", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BuildMart.Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("BuildMart.Domain.Entities.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BuildMart.Domain.Entities.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BuildMart.Domain.Entities.Product", b =>
                {
                    b.HasOne("BuildMart.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("BuildMart.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("BuildMart.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BuildMart.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("BuildMart.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BuildMart.Domain.Entities.ApplicationUser", b =>
                {
                    b.Navigation("Cart");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("BuildMart.Domain.Entities.Cart", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("BuildMart.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("BuildMart.Domain.Entities.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("BuildMart.Domain.Entities.Product", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
